### ISSUE TITLE
Ever Gauzy Server Application for Windows Not Working

### ISSUE THREAD

**Issue by adnan-jamil** [ever-co/ever-gauzy-server#1]
Hi Developers, first of all you guys are doing an amazing Job. I was checking the Ever Gauzy WIndows version and I came to know that there's a server application for windows available. I tried the latest stable version after downloading and installing it. The application crashes without any error or anything. 

It happened for new and old releases. Can you please check what could be the issue?

My specs:
Core i7 10th Gen
16gb ram
Windows 10 19044

**Comment by evereq** [comment]
@adnan-jamil , please try our latest pre-release versions from https://github.com/ever-co/ever-gauzy-server/releases, at least version v0.291.4 works well for us, see below:

![image](https://user-images.githubusercontent.com/118497/232847432-d72a6983-260d-4750-8ba9-00b18558ec03.png)
